/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'
import { Route as BooksNewRouteImport } from './routes/books.new'
import { Route as BooksBookIdIndexRouteImport } from './routes/books.$bookId.index'
import { Route as BooksBookIdEditRouteImport } from './routes/books.$bookId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksNewRoute = BooksNewRouteImport.update({
  id: '/books/new',
  path: '/books/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdIndexRoute = BooksBookIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksBookIdRoute,
} as any)
const BooksBookIdEditRoute = BooksBookIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BooksBookIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ideas': typeof IdeasRoute
  '/books/$bookId': typeof BooksBookIdRouteWithChildren
  '/books/new': typeof BooksNewRoute
  '/books/': typeof BooksIndexRoute
  '/books/$bookId/edit': typeof BooksBookIdEditRoute
  '/books/$bookId/': typeof BooksBookIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ideas': typeof IdeasRoute
  '/books/new': typeof BooksNewRoute
  '/books': typeof BooksIndexRoute
  '/books/$bookId/edit': typeof BooksBookIdEditRoute
  '/books/$bookId': typeof BooksBookIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ideas': typeof IdeasRoute
  '/books/$bookId': typeof BooksBookIdRouteWithChildren
  '/books/new': typeof BooksNewRoute
  '/books/': typeof BooksIndexRoute
  '/books/$bookId/edit': typeof BooksBookIdEditRoute
  '/books/$bookId/': typeof BooksBookIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ideas'
    | '/books/$bookId'
    | '/books/new'
    | '/books/'
    | '/books/$bookId/edit'
    | '/books/$bookId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ideas'
    | '/books/new'
    | '/books'
    | '/books/$bookId/edit'
    | '/books/$bookId'
  id:
    | '__root__'
    | '/'
    | '/ideas'
    | '/books/$bookId'
    | '/books/new'
    | '/books/'
    | '/books/$bookId/edit'
    | '/books/$bookId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdeasRoute: typeof IdeasRoute
  BooksBookIdRoute: typeof BooksBookIdRouteWithChildren
  BooksNewRoute: typeof BooksNewRoute
  BooksIndexRoute: typeof BooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/new': {
      id: '/books/new'
      path: '/books/new'
      fullPath: '/books/new'
      preLoaderRoute: typeof BooksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId/': {
      id: '/books/$bookId/'
      path: '/'
      fullPath: '/books/$bookId/'
      preLoaderRoute: typeof BooksBookIdIndexRouteImport
      parentRoute: typeof BooksBookIdRoute
    }
    '/books/$bookId/edit': {
      id: '/books/$bookId/edit'
      path: '/edit'
      fullPath: '/books/$bookId/edit'
      preLoaderRoute: typeof BooksBookIdEditRouteImport
      parentRoute: typeof BooksBookIdRoute
    }
  }
}

interface BooksBookIdRouteChildren {
  BooksBookIdEditRoute: typeof BooksBookIdEditRoute
  BooksBookIdIndexRoute: typeof BooksBookIdIndexRoute
}

const BooksBookIdRouteChildren: BooksBookIdRouteChildren = {
  BooksBookIdEditRoute: BooksBookIdEditRoute,
  BooksBookIdIndexRoute: BooksBookIdIndexRoute,
}

const BooksBookIdRouteWithChildren = BooksBookIdRoute._addFileChildren(
  BooksBookIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdeasRoute: IdeasRoute,
  BooksBookIdRoute: BooksBookIdRouteWithChildren,
  BooksNewRoute: BooksNewRoute,
  BooksIndexRoute: BooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
