/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as BooksBookIdRouteImport } from './routes/books.$bookId'
import { Route as BooksNewRouteImport } from './routes/books.new'
import { Route as BooksBookIdIndexRouteImport } from './routes/books.$bookId.index'
import { Route as BooksBookIdChaptersRouteImport } from './routes/books.$bookId.chapters'
import { Route as BooksBookIdCharactersRouteImport } from './routes/books.$bookId.characters'
import { Route as BooksBookIdEditRouteImport } from './routes/books.$bookId.edit'
import { Route as BooksBookIdLocationsRouteImport } from './routes/books.$bookId.locations'
import { Route as BooksBookIdOutlineRouteImport } from './routes/books.$bookId.outline'
import { Route as BooksBookIdWorldRouteImport } from './routes/books.$bookId.world'
import { Route as BooksBookIdWriteChapterIdRouteImport } from './routes/books_.$bookId.write.$chapterId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksNewRoute = BooksNewRouteImport.update({
  id: '/books/new',
  path: '/books/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdIndexRoute = BooksBookIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksBookIdRoute,
} as any)
const BooksBookIdChaptersRoute = BooksBookIdChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => BooksBookIdRoute,
} as any)
const BooksBookIdCharactersRoute = BooksBookIdCharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => BooksBookIdRoute,
} as any)
const BooksBookIdEditRoute = BooksBookIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => BooksBookIdRoute,
} as any)
const BooksBookIdLocationsRoute = BooksBookIdLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => BooksBookIdRoute,
} as any)
const BooksBookIdOutlineRoute = BooksBookIdOutlineRouteImport.update({
  id: '/outline',
  path: '/outline',
  getParentRoute: () => BooksBookIdRoute,
} as any)
const BooksBookIdWorldRoute = BooksBookIdWorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => BooksBookIdRoute,
} as any)
const BooksBookIdWriteChapterIdRoute =
  BooksBookIdWriteChapterIdRouteImport.update({
    id: '/books_/$bookId/write/$chapterId',
    path: '/books/$bookId/write/$chapterId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ideas': typeof IdeasRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/books/$bookId': typeof BooksBookIdRouteWithChildren
  '/books/new': typeof BooksNewRoute
  '/books/': typeof BooksIndexRoute
  '/books/$bookId/chapters': typeof BooksBookIdChaptersRoute
  '/books/$bookId/characters': typeof BooksBookIdCharactersRoute
  '/books/$bookId/edit': typeof BooksBookIdEditRoute
  '/books/$bookId/locations': typeof BooksBookIdLocationsRoute
  '/books/$bookId/outline': typeof BooksBookIdOutlineRoute
  '/books/$bookId/world': typeof BooksBookIdWorldRoute
  '/books/$bookId/': typeof BooksBookIdIndexRoute
  '/books/$bookId/write/$chapterId': typeof BooksBookIdWriteChapterIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ideas': typeof IdeasRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/books/new': typeof BooksNewRoute
  '/books': typeof BooksIndexRoute
  '/books/$bookId/chapters': typeof BooksBookIdChaptersRoute
  '/books/$bookId/characters': typeof BooksBookIdCharactersRoute
  '/books/$bookId/edit': typeof BooksBookIdEditRoute
  '/books/$bookId/locations': typeof BooksBookIdLocationsRoute
  '/books/$bookId/outline': typeof BooksBookIdOutlineRoute
  '/books/$bookId/world': typeof BooksBookIdWorldRoute
  '/books/$bookId': typeof BooksBookIdIndexRoute
  '/books/$bookId/write/$chapterId': typeof BooksBookIdWriteChapterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ideas': typeof IdeasRoute
  '/notes': typeof NotesRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRoute
  '/books/$bookId': typeof BooksBookIdRouteWithChildren
  '/books/new': typeof BooksNewRoute
  '/books/': typeof BooksIndexRoute
  '/books/$bookId/chapters': typeof BooksBookIdChaptersRoute
  '/books/$bookId/characters': typeof BooksBookIdCharactersRoute
  '/books/$bookId/edit': typeof BooksBookIdEditRoute
  '/books/$bookId/locations': typeof BooksBookIdLocationsRoute
  '/books/$bookId/outline': typeof BooksBookIdOutlineRoute
  '/books/$bookId/world': typeof BooksBookIdWorldRoute
  '/books/$bookId/': typeof BooksBookIdIndexRoute
  '/books_/$bookId/write/$chapterId': typeof BooksBookIdWriteChapterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ideas'
    | '/notes'
    | '/settings'
    | '/tools'
    | '/books/$bookId'
    | '/books/new'
    | '/books/'
    | '/books/$bookId/chapters'
    | '/books/$bookId/characters'
    | '/books/$bookId/edit'
    | '/books/$bookId/locations'
    | '/books/$bookId/outline'
    | '/books/$bookId/world'
    | '/books/$bookId/'
    | '/books/$bookId/write/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ideas'
    | '/notes'
    | '/settings'
    | '/tools'
    | '/books/new'
    | '/books'
    | '/books/$bookId/chapters'
    | '/books/$bookId/characters'
    | '/books/$bookId/edit'
    | '/books/$bookId/locations'
    | '/books/$bookId/outline'
    | '/books/$bookId/world'
    | '/books/$bookId'
    | '/books/$bookId/write/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/ideas'
    | '/notes'
    | '/settings'
    | '/tools'
    | '/books/$bookId'
    | '/books/new'
    | '/books/'
    | '/books/$bookId/chapters'
    | '/books/$bookId/characters'
    | '/books/$bookId/edit'
    | '/books/$bookId/locations'
    | '/books/$bookId/outline'
    | '/books/$bookId/world'
    | '/books/$bookId/'
    | '/books_/$bookId/write/$chapterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IdeasRoute: typeof IdeasRoute
  NotesRoute: typeof NotesRoute
  SettingsRoute: typeof SettingsRoute
  ToolsRoute: typeof ToolsRoute
  BooksBookIdRoute: typeof BooksBookIdRouteWithChildren
  BooksNewRoute: typeof BooksNewRoute
  BooksIndexRoute: typeof BooksIndexRoute
  BooksBookIdWriteChapterIdRoute: typeof BooksBookIdWriteChapterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/new': {
      id: '/books/new'
      path: '/books/new'
      fullPath: '/books/new'
      preLoaderRoute: typeof BooksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId/': {
      id: '/books/$bookId/'
      path: '/'
      fullPath: '/books/$bookId/'
      preLoaderRoute: typeof BooksBookIdIndexRouteImport
      parentRoute: typeof BooksBookIdRoute
    }
    '/books/$bookId/chapters': {
      id: '/books/$bookId/chapters'
      path: '/chapters'
      fullPath: '/books/$bookId/chapters'
      preLoaderRoute: typeof BooksBookIdChaptersRouteImport
      parentRoute: typeof BooksBookIdRoute
    }
    '/books/$bookId/characters': {
      id: '/books/$bookId/characters'
      path: '/characters'
      fullPath: '/books/$bookId/characters'
      preLoaderRoute: typeof BooksBookIdCharactersRouteImport
      parentRoute: typeof BooksBookIdRoute
    }
    '/books/$bookId/edit': {
      id: '/books/$bookId/edit'
      path: '/edit'
      fullPath: '/books/$bookId/edit'
      preLoaderRoute: typeof BooksBookIdEditRouteImport
      parentRoute: typeof BooksBookIdRoute
    }
    '/books/$bookId/locations': {
      id: '/books/$bookId/locations'
      path: '/locations'
      fullPath: '/books/$bookId/locations'
      preLoaderRoute: typeof BooksBookIdLocationsRouteImport
      parentRoute: typeof BooksBookIdRoute
    }
    '/books/$bookId/outline': {
      id: '/books/$bookId/outline'
      path: '/outline'
      fullPath: '/books/$bookId/outline'
      preLoaderRoute: typeof BooksBookIdOutlineRouteImport
      parentRoute: typeof BooksBookIdRoute
    }
    '/books/$bookId/world': {
      id: '/books/$bookId/world'
      path: '/world'
      fullPath: '/books/$bookId/world'
      preLoaderRoute: typeof BooksBookIdWorldRouteImport
      parentRoute: typeof BooksBookIdRoute
    }
    '/books_/$bookId/write/$chapterId': {
      id: '/books_/$bookId/write/$chapterId'
      path: '/books/$bookId/write/$chapterId'
      fullPath: '/books/$bookId/write/$chapterId'
      preLoaderRoute: typeof BooksBookIdWriteChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BooksBookIdRouteChildren {
  BooksBookIdChaptersRoute: typeof BooksBookIdChaptersRoute
  BooksBookIdCharactersRoute: typeof BooksBookIdCharactersRoute
  BooksBookIdEditRoute: typeof BooksBookIdEditRoute
  BooksBookIdLocationsRoute: typeof BooksBookIdLocationsRoute
  BooksBookIdOutlineRoute: typeof BooksBookIdOutlineRoute
  BooksBookIdWorldRoute: typeof BooksBookIdWorldRoute
  BooksBookIdIndexRoute: typeof BooksBookIdIndexRoute
}

const BooksBookIdRouteChildren: BooksBookIdRouteChildren = {
  BooksBookIdChaptersRoute: BooksBookIdChaptersRoute,
  BooksBookIdCharactersRoute: BooksBookIdCharactersRoute,
  BooksBookIdEditRoute: BooksBookIdEditRoute,
  BooksBookIdLocationsRoute: BooksBookIdLocationsRoute,
  BooksBookIdOutlineRoute: BooksBookIdOutlineRoute,
  BooksBookIdWorldRoute: BooksBookIdWorldRoute,
  BooksBookIdIndexRoute: BooksBookIdIndexRoute,
}

const BooksBookIdRouteWithChildren = BooksBookIdRoute._addFileChildren(
  BooksBookIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IdeasRoute: IdeasRoute,
  NotesRoute: NotesRoute,
  SettingsRoute: SettingsRoute,
  ToolsRoute: ToolsRoute,
  BooksBookIdRoute: BooksBookIdRouteWithChildren,
  BooksNewRoute: BooksNewRoute,
  BooksIndexRoute: BooksIndexRoute,
  BooksBookIdWriteChapterIdRoute: BooksBookIdWriteChapterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
